#!/bin/sh
CONFIG=~/.config/twilight
if [ -z $1 ]; then
  option=toggle
else
  option="$1"
fi
if [ $option != "light" ] && [ $option != "dark" ] && [ $option != "toggle" ]; then
  echo "usage: twilight [light|dark|toggle]"
  exit 1
fi

light() {
  echo light > $CONFIG
  ln -sf ~/src/dotfiles/vimcolors.light $HOME/.vimcolors
  ln -sf ~/.plus/gruvbox-light.xresources $HOME/xresources.theme
  # ln -sf ~/src/dotfiles/xsettings.light.`hostname` $HOME/.xsettingsd
}
dark() {
  echo dark > $CONFIG
  ln -sf ~/src/dotfiles/vimcolors.dark $HOME/.vimcolors
  ln -sf ~/.plus/gruvbox-dark.xresources $HOME/xresources.theme
  # ln -sf ~/src/dotfiles/xsettings.dark.`hostname` $HOME/.xsettingsd
}
toggle() {
  if [ `cat $CONFIG` = "dark" ]; then light; else dark; fi
}

$option
xrdb $HOME/.Xresources
