#!/bin/sh
if [ -z $1 ]; then
  echo "usage: twilight [light|dark]"
  exit 1
fi
option="$1"
if [ $option != "light" ] && [ $option != "dark" ]; then
  echo "usage: twilight [light|dark]"
  exit 1
fi
ln -sf ~/src/dotfiles/vimcolors.$option $HOME/.vimcolors
ln -sf ~/src/dotfiles/xsettingsd.$option.$HOSTNAME $HOME/.xsettingsd && killall xsettingsd && exec xsettingsd
